### ISSUE TITLE
gff file error

### ISSUE THREAD

**Issue by sejmodha** [thiesgehrmann/proteny#5]
Hi There, 
I am trying to run proteny which worked fine with the example dataset but failed with following error for my dataset. GFF files seem to fine with other tools but proteny throws error. 
```
Traceback (most recent call last):
  File "../proteny/pipeline_components/checkInput.py", line 77, in <module>
    G = Gutils.readGFF3File(config["genomes"][genome]["gff"])
  File "../proteny/pipeline_components/gff3utils.py", line 99, in readGFF3File
    G.append(parseGFF3entry(row))
  File "../proteny/pipeline_components/gff3utils.py", line 17, in parseGFF3entry
    attr = dict([tuple(x.strip().split('=')[0:2]) for x in attr.split(";") ])
ValueError: dictionary update sequence element #1 has length 1; 2 is required
```

**Comment by thiesgehrmann** [comment]
Hi Sejmodha,

This is a problem with my handling of entries in the gff attribute field that do not have any attribute values. I have pushed a change that has corrected this error, but it could also be temporarily fixed by removing fields in the attribute files that do not have a value.

e.g.

ID=prot1;Name=prot1.definition;IS_PROTEIN

you could remove the IS_PROTEIN field (or simply download the updated version using git pull).

See change at:
https://github.com/thiesgehrmann/proteny/commit/52702d5d3af3c7c8edb22cbedfa0dda4e977ada5?diff=unified#diff-046c84ba722b064fb5ec99c7dc0e8b33
